
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AngganaApsari
 */
public class Frame_1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame_1
     */
    public Frame_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanjangBalok = new javax.swing.JTextField();
        jLebarBalok = new javax.swing.JTextField();
        jTinggiBalok = new javax.swing.JTextField();
        BtnBalok = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jJariBola = new javax.swing.JTextField();
        BtnBola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Masukkan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Masukkan Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 84, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Masukkan Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 120, 30);
        jPanel1.add(jPanjangBalok);
        jPanjangBalok.setBounds(180, 40, 110, 30);
        jPanel1.add(jLebarBalok);
        jLebarBalok.setBounds(180, 80, 110, 30);
        jPanel1.add(jTinggiBalok);
        jTinggiBalok.setBounds(180, 120, 110, 30);

        BtnBalok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBalok.setText("Hitung");
        BtnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBalok);
        BtnBalok.setBounds(180, 180, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 50, 17, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 90, 17, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 130, 17, 14);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 30, 160, 30);
        jPanel2.add(jSisiKubus);
        jSisiKubus.setBounds(60, 80, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(190, 84, 30, 20);

        BtnKubus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnKubus.setText("Volume");
        BtnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(BtnKubus);
        BtnKubus.setBounds(60, 130, 90, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(60, 30, 180, 30);
        jPanel3.add(jJariBola);
        jJariBola.setBounds(60, 80, 120, 30);

        BtnBola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBola.setText("Volume");
        BtnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(BtnBola);
        BtnBola.setBounds(60, 130, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 84, 30, 20);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 524, 320);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 300, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang=Integer.parseInt(jPanjangBalok.getText());
        lebar=Integer.parseInt(jLebarBalok.getText());
        tinggi=Integer.parseInt(jTinggiBalok.getText());
        int hasil=panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnBalokActionPerformed

    private void BtnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi=Integer.parseInt(jSisiKubus.getText());
        int hasil=sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah :"
            +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnKubusActionPerformed

    private void BtnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari=Integer.parseInt(jJariBola.getText());
        float hasil1=(float) (4/3*3.14*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah :"
            +hasil1,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBalok;
    private javax.swing.JButton BtnBola;
    private javax.swing.JButton BtnKubus;
    private javax.swing.JTextField jJariBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLebarBalok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPanjangBalok;
    private javax.swing.JTextField jSisiKubus;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTinggiBalok;
    // End of variables declaration//GEN-END:variables
}
